project_name: kumo

builds:
  - id: kumo
    main: ./cmd/kumo
    binary: kumo
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    builds:
      - kumo
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{ .Os }}_
      {{ .Arch }}

release:
  github:
    owner: briheet
    name: Kumo
